version: '3.5'
services:
    mongodb:
        env_file:
            - .env
        image: mongo:latest
        # container_name: 'mern-blue-print-db'
        networks:
            - mern-blue-print-network
        restart: on-failure
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}

    mern-blue-print:
        build: .
        image: 'mern-blue-print:0.5'
        container_name: 'mern-blue-print-services'
        restart: on-failure
        networks:
            - mern-blue-print-network
        ports:
            - '4000:4000'
        depends_on:
            - mongodb

networks:
    mern-blue-print-network:
        external: false
        name: mern-blue-print-network
